### ISSUE TITLE
Existing sources crash the `app add` operation

### ISSUE THREAD

**Issue by CSBonLaboratory** [CSBonLaboratory/Unikraft-Scanner#2]
Traceback (most recent call last):
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/coverage.py", line 224, in <module>
    main()
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/coverage.py", line 208, in main
    add_app.add_app_subcommand(args.app, build_dir, args.tag, app_format)
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/add_app.py", line 511, in add_app_subcommand
    analyze_application_sources(compilation_tag, app_build_dir, app_dir)
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/add_app.py", line 410, in analyze_application_sources
    get_source_compile_coverage(
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/add_app.py", line 247, in get_source_compile_coverage
    source_status : SourceStatus = is_new_source(src_path, app_dir)
  File "/home/karakitay/Desktop/Unikraft-Scanner/compilation_coverage_src/add_app.py", line 66, in is_new_source
    if GitCommitStrategy.version_key in latest_version and GitCommitStrategy.version_key in existing_source:
TypeError: argument of type 'SHA1Strategy' is not iterable

**Comment by CSBonLaboratory** [comment]
it seems the problem is caused when a same source file is compiled both in normal mode and isr mode.

**Comment by CSBonLaboratory** [comment]
Fixed
